# Generated by Django 3.0.2 on 2020-08-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('for_plan', models.IntegerField()),
                ('is_directly', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('contact', models.TextField()),
                ('note', models.TextField()),
                ('start_date', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
