# Generated by Django 3.0.2 on 2020-08-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_project',
            name='cost',
        ),
    ]
