# Generated by Django 3.0.2 on 2020-08-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venus', '0002_remove_tbl_project_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_project',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_project',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
